name: Check for GraphBLAS updates
# Checks for latest SuiteSparse:GraphBLAS version on GitHub and creates a PR to update the version used by this repo.
# If there is a new version of GraphBLAS:
#  * Check for a branch called `auto_update_gb_version`. If one exists then exit. If not, push GB update to that branch.
#  * Create a PR from `auto_update_gb_version` branch.

# In addition to permissions below, must explicitly allow GitHub Actions to create pull requests.
# This setting can be found in a repository's settings under Actions > General > Workflow permissions.
# https://github.com/peter-evans/create-pull-request#workflow-permissions
permissions:
  contents: write
  pull-requests: write

on:
  # Note: Workflow must run at least once to appear in workflows list. Easy way to do that is to use a push trigger (and disable it later).
  push:

  # Note: Workflow must exist in main branch for workflow dispatch option to appear
  workflow_dispatch:

  # Enable cron to check for updates once a day:
#  schedule:
#    - cron:  '0 0 * * *'

jobs:
  gb_version_check:
    name: Check for GraphBLAS update
    if: github.repository == 'GraphBLAS/python-suitesparse-graphblas' || github.repository == 'alugowski/python-suitesparse-graphblas'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Get latest GraphBLAS version
        run: |
          python latest_suitesparse_graphblas_version.py > GB_VERSION.txt
          echo "GB_VERSION=$(cat GB_VERSION.txt)" >> $GITHUB_ENV
        shell: bash

#      - name: Determine if update required
#        # there is an update if GB_VERSION.txt has a diff and there is no existing auto update branch
#        run: |
#          if [[ -n "$(git diff --exit-code GB_VERSION.txt)" ]]; then
#            echo "There is a new version: $(cat GB_VERSION.txt)"
#            if [[ -z "$(git branch -r --list origin/auto_update_gb_version)" ]]; then
#                git branch --list
#                echo "CREATE_PR=1" >> $GITHUB_ENV
#            else
#                echo "Existing update branch found."
#            fi
#          else
#            echo "No update."
#          fi
#        shell: bash

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
#        if: ${{ env.CREATE_PR }}
        with:
          # See documentation: https://github.com/peter-evans/create-pull-request
          # Action behavior: https://github.com/peter-evans/create-pull-request#action-behaviour
          # TL;DR: create a PR if there is a diff, keep it up to date if additional diffs come later, auto close if
          # diff disappears due to outside changes.
          #
          # To trigger tests with this PR set up a Personal Access Token.
#          token: ${{ secrets.PAT }}
          add-paths: GB_VERSION.txt
          commit-message: Update to GraphBLAS ${{ env.GB_VERSION }}
          title: Update to SuiteSparse:GraphBLAS ${{ env.GB_VERSION }}
          body: |
            Auto-generated by `update_graphblas.yml`

            Close then reopen this PR to trigger tests. See [here](https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#triggering-further-workflow-runs) for why automatic triggers do not work.
          branch: auto_update_gb_version
          delete-branch: true
