name: Check for GraphBLAS updates

on:
  # Workflow must run at least once to appear in workflows list. Easy way to do that is to use a push trigger.
  push:

  # Workflow must exist in main branch for workflow dispatch option to appear
  workflow_dispatch:

  # When happy with this then enable cron to check for updates once a day:
#  schedule:
#    - cron:  '0 0 * * *'

# Also must explicitly allow GitHub Actions to create pull requests.
# This setting can be found in a repository's settings under Actions > General > Workflow permissions.
# https://github.com/peter-evans/create-pull-request#workflow-permissions
permissions:
  contents: write
  pull-requests: write

jobs:
  gb_version_check:
    name: Check for GraphBLAS update
    if: github.repository == 'GraphBLAS/python-suitesparse-graphblas' || github.repository == 'alugowski/python-suitesparse-graphblas'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Get latest GraphBLAS version
        run: python latest_suitesparse_graphblas_version.py > GB_VERSION.txt

      - name: Determine if update required
        # there is an update if GB_VERSION.txt has been updated and there is no existing auto update branch
        run: |
          echo "GB_VERSION=$(cat GB_VERSION.txt)" >> $GITHUB_ENV
          if [[ -n "$(git diff --exit-code GB_VERSION.txt)" ]]; then
            echo "There is a new version: $(cat GB_VERSION.txt)"
            if [[ -z "$(git branch -r --list origin/auto_update_gb_version)" ]]; then
                git branch --list
                echo "CREATE_PR=1" >> $GITHUB_ENV
            else
                echo "Existing update branch found"
            fi
          else
            echo "No update."
          fi
        shell: bash

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        if: ${{ env.CREATE_PR }}
        with:
            # See documentation: https://github.com/peter-evans/create-pull-request
            add-paths: GB_VERSION.txt
            commit-message: Update to GraphBLAS ${{ env.GB_VERSION }}
            title: Update to GraphBLAS ${{ env.GB_VERSION }}
            body: |
              Auto-generated by `update_graphblas.yml`

              Close then reopen this PR to trigger tests.

              See [here](https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#triggering-further-workflow-runs) for why automatic triggers do not work.
            branch: auto_update_gb_version
            delete-branch: true
